[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "dflow"
version = "0.1.0"
description = "Digital Flow Manager"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name="Michael Hany"}
]

dependencies = [
    "typer",
    "pyyaml",
    "click"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[project.scripts]
dflow = "dflow.cli:app"

[project.urls]
Repository = "https://github.com/Michael-lhany/dflow"
Documentation = "https://github.com/Michael-lhany/dflow/tree/master/docs"

[tool.setuptools.packages.find]
include = ["dflow*"]
exclude = ["Dflow_project_examples*", "tests*"]
